## Build and test as colcon package
foxy-colcon-build:
  stage: build
  image: rduweston/ubuntu-ci:foxy
  before_script:
    - apt-get update && apt-get -y install curl ros-$ROS_DISTRO-xacro
    - echo "deb https://westonrobot.jfrog.io/artifactory/wrtoolbox-release focal main" | tee /etc/apt/sources.list.d/weston-robot.list
    - echo "deb https://westonrobot.jfrog.io/artifactory/wrtoolbox-release focal next" | tee -a /etc/apt/sources.list.d/weston-robot.list
    - curl -sSL 'https://westonrobot.jfrog.io/artifactory/api/security/keypair/wr-deb/public' | apt-key add -
    - apt-get update && apt-get -y install wrp_sdk
  script:
    - mkdir -p /ros2_ws/src 
    # clone/copy source to colcon workspace
    - cp -r /builds/$CI_PROJECT_PATH /ros2_ws/src
    # invoke colcon build
    - cd /ros2_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; colcon build"